#!/bin/bash

VERSION="0.8.0"

~/local/bin/ige-mac-bundler eina.bundle 
cp pango* Eina.app/Contents/Resources/etc/pango/
cp environment.sh Eina.app/Contents/Resources
[ -e "Eina $VERSION.dmg" ] && rm -rf -- "Eina $VERSION.dmg"
hdiutil create -srcfolder Eina.app "Eina $VERSION.dmg"

