#!/bin/bash

VERSION="0.9.1"

# Create app bundle
~/local/bin/ige-mac-bundler eina.bundle
cp pango* Eina.app/Contents/Resources/etc/pango/
cp environment.sh Eina.app/Contents/Resources

# Add extra values to bundle: volume icon
[ -e Eina-$VERSION ] && rm -rf -- Eina-$VERSION
mkdir -p Eina-$VERSION
mv Eina.app Eina-$VERSION
cp "VolumeIcon.icns" "Eina-$VERSION/.VolumeIcon.icns"

# Create dmg
[ -e "Eina-$VERSION.dmg" ] && rm -rf -- "Eina-$VERSION.dmg"
hdiutil create -volname "Eina" -srcfolder "Eina-$VERSION" "Eina-$VERSION.dmg"

