#!/bin/bash

if [ ! -d "$PWD/.git" ]; then
	echo "Run from toplevel"
	exit 1
fi

IFS="
"
for i in $(find . -name '*.c' -o -name '*.h')
do
	grep -q 'Copyright (C) 2004-2010 Eina' $i ||
	(
		set -e
		F="$(echo $i | cut -c 3-)"
		cat tools/gpl-header | sed -e "s,{file},$F,"
		echo
		cat $i
	) > "$i.tmp"
	[ $? -eq 0 ] && mv "$i.tmp" "$i"
done
